on: [push]

name: DeployWidgetApp

env:
  RG_NAME: rg-widget-app
  LOCATION: eastus2

jobs:

  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az group create --name $RG_NAME --location $LOCATION

    - run: |
        az group deployment create -g $RG_NAME --template-file ./arm_template/webservers.deploy.json
        
    - run: |
        echo https://raw.githubusercontent.com/$GITHUB_REPOSITORY/master/script
