on: push

name: nodejs_express_website

env:
  AZURE_WEBAPP_NAME: bootcamp-ctt-test
  AZURE_WEBAPP_PACKAGE_PATH: ./lab_3

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node 12.14.0
        uses: actions/setup-node@v1
        with:
          node-version: "12.4.0"

      - name: npm install, build, and test
        run: |
          cd ./lab_3
          npm install

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
