on: [push]

name: VerifyConnectivity

env:
  RG_NAME: rg-widget-app
  LOCATION: eastus2
  SCRIPT_URI: https://raw.githubusercontent.com/acampb/devopsbootcamp/master/script/build.ps1

jobs:

  connect-to-azure:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
    #- uses: actions/checkout@v2
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI Script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          ls -a $GITHUB_WORKSPACE
          chmod +x $GITHUB_WORKSPACE/lab_1/list_resourcegroups.sh
          $GITHUB_WORKSPACE/lab_1/list_resourcegroups.sh