on: [push]

name: VerifyConnectivity

env:
  RG_NAME: rg-widget-app
  LOCATION: eastus2
  SCRIPT_URI: https://raw.githubusercontent.com/acampb/devopsbootcamp/master/script/build.ps1

jobs:

  connect-to-azure:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Azure CLI Script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          ls -R
          chmod +x /lab_1/list_resourcegroups.sh
          /lab_1/list_resourcegroups.sh